version: '3'

services:
 
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app-nest
    ports:
     - 3000:3000
    restart: always
    tty: true
    networks:
      - api-sgf
    volumes:
      - .:/usr/app-nest/app
  db:
    image: mongo
    ports: 
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INIT_DATABASE: admin
    tty: true
    networks:
      - api-sgf

networks:
  api-sgf: